on: push

jobs:
  x:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: raphaelr/nixpkgs
          ref: gnvim
      - uses: cachix/install-nix-action@v17
      - run: nix-build -A gnvim
