on: push

jobs:
  x:
    runs-on: macos-latest
    #runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          repository: raphaelr/nixpkgs
          ref: pain
      - uses: cachix/install-nix-action@v17
      - run: nix-build --keep-going -A obs-studio-plugins.droidcam-obs
